---
title: "Overrepresentation analysis (ORA)"
output: html_notebook
---
```{r}
#Link for S2IsoMEr package - https://github.com/Bisho2122/S2IsoMEr
#to reinstall and get the updated version

devtools::install_github('Bisho2122/bmetenrichr')
```

```{r}
library(bmetenrichr)
library(reticulate)
```

```{r}
#Load in all differential analysis top hits of either upregulated or downregulated metabolites into a list
markers = list()
conds = c("A498","BT-549","HOP-62","HS 578T","HT29","HeLa","IGR-OV1", "NCI-H460","MALME-3M","OVCAR-5")

for (i in conds) {
  up <- read.csv(file = paste0("C:/Users/Jeany/Documents/HTSpaceM/data/ORA/SC2_",i,"_formulas_top-up.csv"), sep = ",", header = FALSE)
  up <- gsub("^'|'$", "", unlist(up, use.names = FALSE)) #returns character vector of metabolites
  down <- read.csv(file = paste0("C:/Users/Jeany/Documents/HTSpaceM/data/ORA/SC2_",i,"_formulas_top-down.csv"), sep = ",", header = FALSE)
  down <- gsub("^'|'$", "", unlist(down, use.names = FALSE))
  #'markers' contains all conditions (up and down) to run in ORA analysis
  markers[[paste0(i,"_up")]] = up
  markers[[paste0(i,"_down")]] = down
}
```

```{r}
#generate "custom universe" for the molecule background of ORA analysis, which is all annotated metabolites of our analysis
all_detected_mols <- read.csv(file = paste0("C:/Users/Jeany/Documents/HTSpaceM/data/ORA/SC2_formula_background.csv"), sep = ",", header = FALSE)
all_detected_mols <- gsub("^'|'$", "", unlist(all_detected_mols, use.names = FALSE))
```

```{r}
#run ORA for molecule classes
background_db_class <- bmetenrichr::Load_background(mol_type = "Metabo", bg_type = "sub_class", feature_type = "sf")  #bg_type can be: "main_class", "super_class", "sub_class" and "pathways"

SC_ORA_classes <- Run_simple_ORA(marker_list = markers, background = background_db_class, custom_universe = all_detected_mols, min_intersection = 2, alpha_cutoff = 1)
```

```{r}
write.csv(SC_ORA_classes, file="C:/Users/Jeany/Documentos/HTSpaceM/data/SC2_ORA_sub-classes.csv")
```

```{r}
#run ORA for pathways
background_db_path <- bmetenrichr::Load_background(mol_type = "Metabo", bg_type = "pathways", feature_type = "sf")

SC_ORA_pathways <- Run_simple_ORA(marker_list = markers, background = background_db_path, custom_universe = all_detected_mols, min_intersection = 2, alpha_cutoff = 1)
```

```{r}
write.csv(SC_ORA_pathways, file="C:/Users/Jeany/Documentos/HTSpaceM/data/SC2_ORA_pathways.csv")
```
